### ISSUE TITLE
Add support for additional query languages

### ISSUE THREAD

**Issue by mcupak** [ga4gh/data-connect#113]
Promote extensible, evolving framework; add support for new query languages—including GraphQL.

More info: https://docs.google.com/document/d/1xIHFWRisQJ27f5Cc4l0djEDx87-f-Oid3356AP74-0k/edit?ts=606dc807#

**Comment by NehaAr** [comment]
N1QL is also a good language. It provides extensive support for JSON objects

**Comment by mcupak** [comment]
We're still open to the idea of introducing additional query languages, but there isn't bandwidth in the current group to address this. Will reopen as needed.
