### ISSUE TITLE
Use of underscore as separator in dataset/{id}_{pageNumber}

### ISSUE THREAD

**Issue by cmungall** [ga4gh/data-connect#23]
In https://github.com/ga4gh-discovery/ga4gh-discovery-search#dataset-in-a-bucket-no-code-implementation

you have a path `dataset/{id}_{pageNumber}`

This is ambiguous unless you forbid IDs from containing underscores - is there a specification of IDs? Isn't it more customary to use http params for paging?

**Comment by jfuerth** [comment]
Hi @cmungall 

Thanks for the question. I agree that, in general, `_` is not a safe delimiter between an ID and a page number. This was meant to be an example, not a requirement. Reading it in the context of your question, I agree it comes across as prescriptive.

Query parameters are indeed common and you could use them if your server supports it (more on this below). Any of these would also satisfy the specification as written:

* `/table/{table_name}/data_pages/{pageNumber}`
* `data_pages/{pageNumber}` (relative to the referring resource, `/table/{table_name}/data`)
* `/table/{table_name}/data?page={pageNumber}`
* `/table/{table_name}/pages/{pageNumber}`
* `/table/{table_name}/p{pageNumber}`
* `https://example.com/collections/x44y.br7/table/{table_name}/data?page={pageNumber}`

In fact, the pages need not be numbered at all. All that matters is that the server recognizes the URL and serves the correct page in response.

* `table/{table_name}/data_pages/hello`
* `table/{table_name}/data?foo=yes`

The Search/Tables API simply says the next page link can be any relative or absolute URL. Server-side implementations are free to choose a pagination strategy that works best for them. Clients are required to be able to resolve the link whether it's relative or absolute, with or without query parameters.

Finally, why not use a query parameter for page number in this specific use case? We were describing a way of implementing this specification simply by uploading a collection of JSON files to a cloud storage bucket (eg. Amazon S3, Google Cloud Storage, or Azure Blobstore). In these systems, each file has to have its own path. In this scenario, we can't pile all the pages onto the same path and use query params to select between them.

I'll leave this issue open for feedback and if this explanation makes sense to you, we'll update the example to be clearer about the use case.

**Comment by ifokkema** [comment]
Just passing by here on my search for existing APIs when planning to build a new one on top of [LOVD3](/LOVDnl/LOVD3). I think the above information would be very valuable to be added to the docs. In my use case, I'm personally thinking about providing pagination in the sense of a genomic location, so "normal" page numbers don't suit me, either.

**Comment by jfuerth** [comment]
Thanks @ifokkema. If you have a moment, I would appreciate your review on PR #100.

**Comment by ifokkema** [comment]
Looks great, @jfuerth! Thanks!
