### ISSUE TITLE
Release Tables API as 0.1

### ISSUE THREAD

**Issue by mcupak** [ga4gh/data-connect#26]
Since we now have multiple implementations using the Tables API as is in `develop`, I wonder if it makes sense to release the current state as 0.1 to have a stable state to refer to, and target the Search/Query part for 0.2.

@kemp-google @jfuerth WDYT?

**Comment by jfuerth** [comment]
Sure, that sounds useful to me. Better than having a bunch of implementations that claim to target a snapshot.

**Comment by mcupak** [comment]
https://github.com/ga4gh-discovery/ga4gh-discovery-search/releases/tag/0.1
