### ISSUE TITLE
Exporting large search results

### ISSUE THREAD

**Issue by jvlasblom** [ga4gh/data-connect#45]
### Problem
Large search results may be expensive or slow to transfer large search results, and the data host may need to shift these costs to the user.  "Requester-pays" seems hard to implement currently, as the cost of egress from the search implementation to the end-user isn't easily billed to that user.    What follows is a rough sketch of how an export function might work to solve this problem.

### Proposal
The search spec could be modified to allow one to specify a "destination" where results will be written.  It is up to the querier to set permissions on this destination appropriately to allow the search implementation to write to it.  e.g.

```
POST /search

{
  query: "select foo..."
  destination: "s3://my-bucket/result1"
}
```

The response could include or be a job record, :
```
{
    start_time: "...",
    end_time: "...",
    job_status: "RUNNING",
    destination: "s3://my-bucket/result1"
}
```

If the search implementation is not authorized to write to the destination, this should be indicated to the user with an appropriate error response.  If the destination is in a region the search implementation will not write to (due to costs or geographic restrictions), this should also be clearly indicated to the user in an error response.

The job status "COMPLETE" will indicate when the export is done and the file is available.

### Benefits:
- The search implementation can choose to reject writes to regions where egress fees would be incurred, and egress from the user's bucket will be billed to the user.  

- Transfer of large query results can occur using cloud-provider tools optimized for large transfers, which many users will already be familiar with.    This can simplify the implementation of search, and prevent funnelling large amounts of data through the search node(s).  Parallel runs of a workflow may benefit from using the same exported file.   Quotas can be defined limiting the amount of data returned via paginated JSON, encouraging users to export large results.   

- (Possibly out of scope?)  An optional 'format' parameter can control the format of the export (JSON,  CSV,  etc., or perhaps more specialized formats like VCF).  One format could be 'tables', which would generate static [tables-in-a-bucket](https://github.com/ga4gh-discovery/ga4gh-discovery-search#tables-in-a-bucket-no-code-implementation) at the requested destination.

**Comment by mcupak** [comment]
We've decided to close this issue for now at the specification level given how implementation-specific it is. If there is a use case and an existing implementation using this approach, we'd be open to consider formalizing it as part of the standard.
