### ISSUE TITLE
Tables-in-a-bucket docs broken

### ISSUE THREAD

**Issue by mcupak** [ga4gh/data-connect#52]
"The link to the GA4GH example in the docs is borked. I can see the table endpoint (https://storage.googleapis.com/ga4gh-tables-example/tables) but not the docs (https://storage.googleapis.com/ga4gh-tables-example/EXAMPLE.md)."

This is referring to [the last line in this section of the docs](https://github.com/ga4gh-discovery/ga4gh-search#tables-in-a-bucket-no-code-implementation).

**Comment by mcupak** [comment]
I've checked the file does not exist in the bucket and I don't remember what it originally referred to (@jfuerth do you?). With the new docs we have now, I think we can probably just remove it.

**Comment by jfuerth** [comment]
No, I don't remember what that EXAMPLE.md file was. The contents of that bucket have been recreated several times to keep up with changes in the spec, and the markdown file must have been lost along the way.
