### ISSUE TITLE
Review approach to pagination of Search results

### ISSUE THREAD

**Issue by ianfore** [ga4gh/data-connect#61]
PRC review raised the question of how pagination works. Discussed in the [PRC report here](https://docs.google.com/document/d/1VP7sLqijKvaEraVEAZrxQAa-3VP--AETeWOV5g7-s6U).

The responses there note that a number of approaches exist to do pagination in REST services, but no standard.

Investigated  how FHIR does pagination of search results.

This is from the NCPI FHIR server which uses the following approach.
```
 "link": [ {
   "relation": "self",
   "url": "http://localhost:8000/Patient?gender=female"
 }, {
   "relation": "next",
   "url": "http://localhost:8000?_getpages=141093b6-8c4b-4fa5-8b9f-a302914572eb&_getpagesoffset=50&_count=50&_bundletype=searchset"
 } ]
```

That server uses FHIR HAPI as an implementation. Requires follow up as to whether the approach taken is part of the FHIR spec or part of the HAPI implementation.

**Comment by mcupak** [comment]
TASC is working on this, let's hold off until it's resolved there.

**Comment by mcupak** [comment]
This has been superseded by work in TASC, closing.
