### ISSUE TITLE
Migrate away from travis-ci.org before it shuts down

### ISSUE THREAD

**Issue by mcupak** [ga4gh/data-connect#63]
Switch to travis-ci.com (or GitHub actions?) before travis-ci.org goes readonly at the end of the year:

https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom

**Comment by jb-adams** [comment]
I've begun migrating some GA4GH specs and projects to travis-ci.com , I think the same could be done here if it works for the Search team. There's a limited free tier. We've discussed at secretariat a tech budget, which could include subscriptions for things like Travis CI. Though nothing concrete has been put in motion yet
