### ISSUE TITLE
Clyde theme needs to be versioned for submodules

### ISSUE THREAD

**Issue by gewenyu99** [ga4gh/data-connect#82]
This is sketchy: https://github.com/ga4gh-discovery/ga4gh-search/blob/release-1.0.0/.travis.yml#L15-L18, the builds can break due to Clyde updates.

We can add a Clyde version branch

**Comment by mcupak** [comment]
@gewenyu99 Is this still an issue?

**Comment by gewenyu99** [comment]
@mcupak No, I'll close this. I fixed this already when I fixed the make file. Submodules will point only to a commit hash, so this isn't an issue anyway.
