### ISSUE TITLE
Provide links to download clients in the docs

### ISSUE THREAD

**Issue by mcupak** [ga4gh/data-connect#91]

**Comment by gewenyu99** [comment]
We have a section in the introduction to download the clients: https://ga4gh-discovery.github.io/ga4gh-search/docs/getting-started/introduction/#installing-client-libraries

Maybe I should link to that section in multiple places, or somehow make it more prominent?

**Comment by mcupak** [comment]
You're right, I missed that. I'd expect all client things on the same page - maybe "Consume data" should be that page? WDYT?
