### ISSUE TITLE
{S}[B] links in SEARCHSPEC.md

### ISSUE THREAD

**Issue by mbaudis** [ga4gh/data-connect#96]
In SEARCHSPEC.md there is at least one reference to a non-existing schema:

https://schemablocks.org/schemas/example/blood-group/v1.0.0

**Comment by jfuerth** [comment]
Thanks for catching that. It was meant to be a hypothetical example. I will change it to use example.com for clarity.

**Comment by mbaudis** [comment]
Well, I actually would like an {S}[B] example :-)  How about using https://github.com/ga4gh-schemablocks/playground for such cases?!

**Comment by jfuerth** [comment]
Sure, sounds like a good plan. I don't feel that I know enough about blood groups to propose a serious definition for Blood Group, but I'm happy to put what we've sketched up into the playground!

Is a PR with a BloodGroup.yaml file at https://github.com/ga4gh-schemablocks/playground/tree/master/schemas all that's needed?

**Comment by mbaudis** [comment]
In principle, yes. And then it has to be processed - in a local version containing the relevant sb repos - see https://github.com/ga4gh-schemablocks/tools/blob/master/README.md

There is some documentation at [sb](https://schemablocks.org/about/repositories.html); but cave - this is the original setup and

* may be tooled more elegantly (well, should)
* may be broken :-?

I'm happy to help if you add a file, so I can warm this up again & then we'll take it from there. Anything "playground" is up for grabs; and any re-tooling is fine with me (though in principle I like the outcome/produced structure, but even there I'm open).

**Comment by jfuerth** [comment]
Okay, thanks! This is on my to-do list now.
