### ISSUE TITLE
README.md: "rectangular" data only?

### ISSUE THREAD

**Issue by ifokkema** [ga4gh/data-connect#97]
Hi all,
A probably minor thing; the `README.md` mentions twice that GA4GH Search can be used for any "rectangular" data. This suggested to me that GA4GH Search can be used *only* for "rectangular" data, so I nearly discarded the idea of using this format. However, digging further, [examples](https://github.com/ga4gh-discovery/ga4gh-search/blob/develop/TABLE.md) show that luckily it isn't, and objects can also be included. Perhaps it would be good to have this included in the explanation in the readme?

**Comment by jfuerth** [comment]
Great point, thank you. I've pushed a change in PR #101.
